# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: crs-toolchain
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - id: "crs-toolchain"
    env:
      - CGO_ENABLED=0
    binary: crs-toolchain
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs'
      - '^test'
release:
  prerelease: auto
dockers:
    - image_templates:
          - "ghcr.io/coreruleset/crs-toolchain:{{ .Version }}-amd64"
      use: buildx
      goarch: amd64
      build_flag_templates:
          - "--platform=linux/amd64"
    - image_templates:
          - "ghcr.io/coreruleset/crs-toolchain:{{ .Version }}-arm64"
      use: buildx
      goarch: arm64
      build_flag_templates:
          - "--platform=linux/arm64"
docker_manifests:
    - name_template: "ghcr.io/coreruleset/crs-toolchain:latest"
      image_templates:
          - "ghcr.io/coreruleset/crs-toolchain:{{ .Version }}-amd64"
          - "ghcr.io/coreruleset/crs-toolchain:{{ .Version }}-arm64"
    - name_template: "ghcr.io/coreruleset/crs-toolchain:{{ .Version }}"
      image_templates:
          - "ghcr.io/coreruleset/crs-toolchain:{{ .Version }}-amd64"
          - "ghcr.io/coreruleset/crs-toolchain:{{ .Version }}-arm64"
nfpms:
  - id: "crs-toolchain"
    builds: ["crs-toolchain"]
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    file_name_template: '{{ .ConventionalFileName }}'
    vendor: OWASP Core Rule Set Project
    homepage: https://github.com/Traceableai/crs-toolchain
    maintainer: maxleske@gmail.com
    description:
      CRS ToolChain helper

    license: APL2

announce:
  slack:
    enabled: true
    message_template: >
      {{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}
    channel: '#coreruleset-notify'
    username: 'Releaser'
    icon_emoji: ':new:'
    attachments: []
